main: ${main.class}
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Dylan Hansch
website: ${project.url}
commands:
    say:
        description: Broadcast message to entire server.
        usage: /<command> <message>
permissions:
    mcsaycustomizer.say:
        description: Broadcast message to entire server.
        default: op
